Just debug session
Signed-off-by: Derek Nola <derek.nola@suse.com>

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -222,7 +222,7 @@ jobs:
         fi
 
   docker-arm64:
-    needs: build-arm64
+    # needs: build-arm64
     name: Docker Tests Arm64
     if: github.repository == 'k3s-io/k3s'
     runs-on: oracle-aarch64-4cpu-16gb
@@ -248,24 +248,24 @@ jobs:
         sudo chmod +x /usr/bin/yq
         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
         sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
-    - name: "Download k3s image"
-      uses: actions/download-artifact@v4
-      with:
-        name: k3s-arm64
-        path: ./dist/artifacts
-    - name: Load k3s image
-      run: docker image load -i ./dist/artifacts/k3s-image.tar
-    - name: Run ${{ matrix.dtest }} Test
-      run: |
-        mv ./dist/artifacts/k3s-arm64 ./dist/artifacts/k3s 
-        chmod +x ./dist/artifacts/k3s
-        . ./scripts/version.sh
-        . ./tests/docker/test-helpers
-        . ./tests/docker/test-run-${{ matrix.dtest }}
-        echo "Did test-run-${{ matrix.dtest }} pass $?"
-    - name: On Failure, Launch Debug Session
+    # - name: "Download k3s image"
+    #   uses: actions/download-artifact@v4
+    #   with:
+    #     name: k3s-arm64
+    #     path: ./dist/artifacts
+    # - name: Load k3s image
+    #   run: docker image load -i ./dist/artifacts/k3s-image.tar
+    # - name: Run ${{ matrix.dtest }} Test
+    #   run: |
+    #     mv ./dist/artifacts/k3s-arm64 ./dist/artifacts/k3s 
+    #     chmod +x ./dist/artifacts/k3s
+    #     . ./scripts/version.sh
+    #     . ./tests/docker/test-helpers
+    #     . ./tests/docker/test-run-${{ matrix.dtest }}
+    #     echo "Did test-run-${{ matrix.dtest }} pass $?"
+    - name: Launch Debug Session
       uses: dereknola/action-upterm@v1.1
-      if: ${{ failure() }}
+      # if: ${{ failure() }}
       with:
         ## If no one connects after 5 minutes, shut down server.
         wait-timeout-minutes: 5
